### ISSUE TITLE
Several images mean calculation inside "caffe-compute-image-mean.py"

### ISSUE THREAD

**Issue by MyVanitar** [bamos/python-scripts#6]
Hello

I have questions of this script: `caffe-compute-image-mean.py`:

1) where should I define the path to the directory where it contains the images?

2) How can I get the mean value as a written text, I mean something like this: 
`(104.00698793, 116.66876762, 122.67891434)`

**Comment by bamos** [comment]
1 - See `parser`, you provide it with `imageDir`.
2 - You can print out `mean` after it's computed

**Comment by VanitarNordic** [comment]
Thank you very much.

May I ask you what is this in parser? `Prefix of the mean file.`

**Comment by MyVanitar** [comment]
@bamos 

Hello again. I used the script but I get `nan` values:

![screenshot from 2017-04-24 13-33-18](https://cloud.githubusercontent.com/assets/18719591/25329884/d70fe8ae-28f2-11e7-8f90-4a3c82775e37.png)
